// evmone: Fast Ethereum Virtual Machine implementation
// Copyright 2026 The evmone Authors.
// SPDX-License-Identifier: Apache-2.0
#pragma once

#include <test/utils/test_driver.hpp>
#include <filesystem>
#include <span>
#include <vector>

namespace evmone::test
{
/// The JSON test files under @p root, sorted, so a run visits them in a stable order.
/// "index.json" is skipped: those are lists of tests generated by other tools, not tests.
[[nodiscard]] std::vector<std::filesystem::path> collect_test_files(
    const std::filesystem::path& root);

/// Drops from @p files everything under one of the @p ignored paths, which are relative to
/// @p root. Whole path components are matched, so ignoring "bc4895" keeps "bc4895-withdrawals".
void ignore_test_files(std::vector<std::filesystem::path>& files, const std::filesystem::path& root,
    std::span<const std::filesystem::path> ignored);

/// Adds to @p cases one test per fixture file under @p root, which is that file itself when it
/// is not a directory. The tests hold @p options and @p vm by reference, so both must outlive
/// them.
void collect_tests(std::vector<TestCase>& cases, const std::filesystem::path& root,
    const RunOptions& options, evmc::VM& vm);

/// Runs the Ethereum tests collected under every path in @p roots, reporting to @p out.
/// Returns the process exit code.
[[nodiscard]] int test(evmc::VM& vm, std::span<const std::filesystem::path> roots,
    const RunOptions& options, std::ostream& out);
}  // namespace evmone::test
